import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "./ui/fonts";
import Hero from "./ui/hero";

export const metadata: Metadata = {
  title: "Primo MOS Barber Shop",
  description: "Generated by create next app",
};

const heading = "Primo MOS";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className="scroll-smooth">
      <body className={poppins.className}>
        <Hero heading={heading} />
        {children}
      </body>
    </html>
  );
}
